---
# tasks file for vitalied.memcached

- name: apt-get install
  apt:
    name: memcached
    state: latest
  notify: restart memcached
  tags: vitalied.memcached

- name: copy templates
  template:
    src: etc/memcached.conf.j2
    dest: /etc/memcached.conf
  notify: restart memcached
  tags: vitalied.memcached
